# Generated by Django 2.1.11 on 2019-11-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0008_itinerary_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='title',
        ),
    ]
