# Generated by Django 2.1.11 on 2019-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0009_remove_itinerary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
