# Generated by Django 2.1.11 on 2019-12-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0017_auto_20191128_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='position',
            field=models.FloatField(null=True),
        ),
    ]
