# Generated by Django 2.1.11 on 2019-12-10 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('itinerary', '0021_set_itineraryitem_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryitem',
            options={'ordering': ['position']},
        ),
    ]
