# Generated by Django 2.2.10 on 2020-03-13 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('itinerary', '0036_auto_20200309_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerarysettings',
            old_name='target_itinerary_length',
            new_name='target_length',
        ),
    ]
