# Generated by Django 2.2.10 on 2020-04-14 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0040_auto_20200414_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarysettings',
            name='target_length',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(
                1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
