# Generated by Django 3.0.7 on 2020-07-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0050_auto_20200706_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcodesettings',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_code_settings', to='itinerary.Itinerary'),
        ),
    ]
