# Generated by Django 2.1.11 on 2019-11-19 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0012_auto_20191119_0859"),
        ("users", "0006_team"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="members",),
        migrations.DeleteModel(name="Team",),
    ]
