# Generated by Django 3.1 on 2020-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_teamsettings_team_type'),
        ('users', '0009_auto_20200915_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_settings',
            field=models.ManyToManyField(blank=True, related_name='team_settings', to='planner.TeamSettings'),
        ),
    ]
