# Generated by Django 2.1.9 on 2019-11-04 10:46

from django.db import migrations
import apps.users.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191104_1040'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.user_manager.UserManager()),
            ],
        ),
    ]
