# Generated by Django 2.1.15 on 2020-01-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accesslogs', '0002_logentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='request_meta',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='request_uri',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='request_user_email',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='request_user_id',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='response_status_code',
            field=models.CharField(editable=False, max_length=3),
        ),
    ]
