CREATE TABLE public.import_adres
(
    adres_id numeric(64,0),
    straatcode numeric(64,0),
    postcode character varying(6) COLLATE pg_catalog."default",
    sdl_code character varying(1) COLLATE pg_catalog."default",
    brt_code character varying(1) COLLATE pg_catalog."default",
    pvh_cd character varying(2) COLLATE pg_catalog."default",
    pvh_omschr character varying(45) COLLATE pg_catalog."default",
    sbw_omschr character varying(64) COLLATE pg_catalog."default",
    sbv_omschr character varying(64) COLLATE pg_catalog."default",
    wzs_id integer NOT NULL DEFAULT nextval('import_adres_wzs_id_seq'::regclass),
    wzs_buurtcode_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_buurtnaam_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_buurtcombinatiecode_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_buurtcombinatienaam_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_22gebiedencode_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_22gebiedennaam_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_rayoncode_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_rayonnaam_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_stadsdeelcode_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_stadsdeelnaam_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_alternatieve_buurtennaam_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_alternatieve_buurtencode_os_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_update_datumtijd timestamp without time zone,
    wzs_geom geometry(Point,4326),
    wzs_lon double precision,
    wzs_lat double precision,
    wzs_wijze_verrijking_geo character varying(255) COLLATE pg_catalog."default",
    wzs_22gebiedencode_2015 character varying(255) COLLATE pg_catalog."default",
    wzs_22gebiedennaam_2015 character varying(255) COLLATE pg_catalog."default",
    sttnaam character varying(64) COLLATE pg_catalog."default",
    hsnr bigint,
    hsltr character varying(1) COLLATE pg_catalog."default",
    toev character varying(16) COLLATE pg_catalog."default",
    brtcombi_code bigint,
    brtcombi_naam character varying(31) COLLATE pg_catalog."default",
    sdl_naam character varying(32) COLLATE pg_catalog."default",
    xref numeric(9,1),
    yref numeric(9,1),
    brt_naam character varying(64) COLLATE pg_catalog."default",
    a_dam_bag character varying(64) COLLATE pg_catalog."default",
    landelijk_bag character varying(64) COLLATE pg_catalog."default",
    sbw_code numeric(32,0),
    sbv_code numeric(17,1),
    inwnrs numeric(17,1),
    kmrs numeric(17,1),
    hvv_dag_tek text COLLATE pg_catalog."default",
    max_vestig_dtm text COLLATE pg_catalog."default",
    wng_id numeric(64,0),
    CONSTRAINT import_adres_pkey PRIMARY KEY (wzs_id)
)
WITH (
    OIDS = TRUE
)
TABLESPACE pg_default;
