CREATE TABLE public.bwv_personen
(
    id integer,
    pen_type character varying(10) COLLATE pg_catalog."default",
    ads_id_wa integer,
    gezinsverhouding character varying(1) COLLATE pg_catalog."default",
    geslacht character varying(1) COLLATE pg_catalog."default",
    voorletters character varying(5) COLLATE pg_catalog."default",
    a_nr_gezinshoofd character varying(10) COLLATE pg_catalog."default",
    geboortedatum timestamp without time zone,
    a_nr character varying(10) COLLATE pg_catalog."default",
    burgerlijke_staat character varying(1) COLLATE pg_catalog."default",
    naam character varying(30) COLLATE pg_catalog."default",
    sofinr integer,
    dsr_id integer,
    geheim_adres character varying(1) COLLATE pg_catalog."default",
    huwelijksdatum timestamp without time zone,
    echtscheidingsdatum timestamp without time zone,
    overlijdensdatum timestamp without time zone,
    voorv_mnaam character varying(11) COLLATE pg_catalog."default",
    voorv_naam character varying(11) COLLATE pg_catalog."default",
    meisjesnaam character varying(30) COLLATE pg_catalog."default",
    vertrekdatum_adam timestamp without time zone,
    ind_naamgebruik character varying(1) COLLATE pg_catalog."default",
    nat_ned character varying(1) COLLATE pg_catalog."default",
    nat_vreemd integer,
    ind_nat_ovlp character varying(1) COLLATE pg_catalog."default",
    verblijfstatus character varying(2) COLLATE pg_catalog."default",
    datum_einde_vblstat timestamp without time zone,
    landcode character varying(4) COLLATE pg_catalog."default",
    vestigingsdatum_adam timestamp without time zone,
    vestigingsdatum_adres timestamp without time zone,
    user_created character varying(30) COLLATE pg_catalog."default",
    date_created timestamp without time zone,
    user_modified character varying(30) COLLATE pg_catalog."default",
    date_modified timestamp without time zone,
    datum_begin_vblstat timestamp without time zone,
    ais_nr character varying(11) COLLATE pg_catalog."default",
    crv_nr character varying(10) COLLATE pg_catalog."default",
    geheim character varying(1) COLLATE pg_catalog."default",
    anr_ouder_1 character varying(10) COLLATE pg_catalog."default",
    anr_ouder_2 character varying(10) COLLATE pg_catalog."default",
    anr_partner character varying(10) COLLATE pg_catalog."default",
    in_onderzoek character varying(1) COLLATE pg_catalog."default",
    datum_verkrijging_ned timestamp without time zone,
    datum_verlies_ned timestamp without time zone,
    datum_verkrijging_vreemd timestamp without time zone,
    datum_verlies_vreemd timestamp without time zone,
    voorletters_zdia character varying(5) COLLATE pg_catalog."default",
    naam_zdia character varying(30) COLLATE pg_catalog."default",
    voorv_mnaam_zdia character varying(11) COLLATE pg_catalog."default",
    voorv_naam_zdia character varying(11) COLLATE pg_catalog."default",
    meisjesnaam_zdia character varying(30) COLLATE pg_catalog."default",
    nm_dia_255 character varying(1) COLLATE pg_catalog."default",
    mnm_dia_255 character varying(1) COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
