CREATE TABLE public.bwv_woningen
(
    id bigint,
    egr_id integer,
    sbw_code character varying(2) COLLATE pg_catalog."default",
    bron_kamertal_code character varying(1) COLLATE pg_catalog."default",
    bouwjaar_kartotheek_vh smallint,
    type_woning character varying(1) COLLATE pg_catalog."default",
    gbs_gevoelig character varying(1) COLLATE pg_catalog."default",
    hori_gesplitst character varying(1) COLLATE pg_catalog."default",
    begin_woning_code character varying(3) COLLATE pg_catalog."default",
    begin_datum timestamp without time zone,
    pvh_code character varying(2) COLLATE pg_catalog."default",
    afg_code character varying(6) COLLATE pg_catalog."default",
    bva_woonobject character varying(12) COLLATE pg_catalog."default",
    toelichting character varying(255) COLLATE pg_catalog."default",
    vloerhoogte smallint,
    nuttig_woonoppervlak numeric(6,1),
    grondeigendom character varying(1) COLLATE pg_catalog."default",
    hori_gesplitst_datum timestamp without time zone,
    vloeroppervlak_totaal numeric(6,1),
    jaar_renovatie smallint,
    vierde_vertrek_oppervlak numeric(6,1),
    vijfde_vertrek_oppervlak numeric(6,1),
    woningonderzoek character varying(1) COLLATE pg_catalog."default",
    derde_vertrek_oppervlak numeric(6,1),
    einde_datum timestamp without time zone,
    einde_woning_code character varying(2) COLLATE pg_catalog."default",
    overige_ruimten_oppervlak numeric(6,1),
    pdossier_datum timestamp without time zone,
    pdossier_toelichting character varying(255) COLLATE pg_catalog."default",
    kamer_aantal smallint,
    zolderkamer_aantal smallint,
    bad_code smallint,
    bergruimte_code smallint,
    bad_douche_oppervlak numeric(6,1),
    berging_zolder_totaal_oppervla numeric(6,1),
    monument_code smallint,
    keuken_code smallint,
    toilet_code smallint,
    toegang_code smallint,
    cv_en_warmwater_code smallint,
    tuin_code smallint,
    hoofdwoonvertrek_oppervlak numeric(6,1),
    tweede_vertrek_oppervlak numeric(6,1),
    zesde_vertrek_oppervlak numeric(6,1),
    keukens_totaal_oppervlak numeric(6,1),
    zolderkamers_oppervlak numeric(6,1),
    user_created character varying(30) COLLATE pg_catalog."default",
    date_created timestamp without time zone,
    user_modified character varying(30) COLLATE pg_catalog."default",
    date_modified timestamp without time zone,
    corp_id integer,
    verh_nr character varying(15) COLLATE pg_catalog."default",
    sbv_code character varying(2) COLLATE pg_catalog."default",
    obj_nr_vra character varying(14) COLLATE pg_catalog."default",
    status_obj_vra character varying(4) COLLATE pg_catalog."default",
    pnd_nr_vra character varying(14) COLLATE pg_catalog."default",
    sps_nr_vra character varying(14) COLLATE pg_catalog."default",
    lps_nr_vra character varying(14) COLLATE pg_catalog."default",
    shortstay character varying(1) COLLATE pg_catalog."default",
    benb_melding character varying(1) COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
