# Generated by Django 3.1 on 2020-09-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsettings',
            name='team_type',
            field=models.CharField(choices=[['Vakantieverhuur', 'Vakantieverhuur'], ['Onderverhuur', 'Onderverhuur']], default='Vakantieverhuur', max_length=100),
        ),
    ]
