# Generated by Django 3.1 on 2020-09-29 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_observation_observationchoices_situation_situationchoices_suggestnextvisit_suggestnextvisitchoices'),
        ('planner', '0002_teamsettings_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsettings',
            name='observation_choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.observationchoices'),
        ),
    ]
