# Generated by Django 3.1 on 2020-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_auto_20201007_1226"),
        ("planner", "0002_teamsettings_team_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsettings",
            name="project_choices",
            field=models.ManyToManyField(
                blank=True, related_name="team_settings_list", to="cases.Project"
            ),
        ),
        migrations.AddField(
            model_name="teamsettings",
            name="stadia_choices",
            field=models.ManyToManyField(
                blank=True, related_name="team_settings_list", to="cases.Stadium"
            ),
        ),
    ]
