# Generated by Django 3.1 on 2020-10-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_auto_20201006_0721'),
        ('visits', '0008_auto_20201006_0721'),
        ('planner', '0002_teamsettings_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsettings',
            name='observation_choices',
            field=models.ManyToManyField(blank=True, related_name='team_settings_list', to='visits.Observation'),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='project_choices',
            field=models.ManyToManyField(blank=True, related_name='team_settings_list', to='cases.Project'),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='situation_choices',
            field=models.ManyToManyField(blank=True, related_name='team_settings_list', to='visits.Situation'),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='stadia_choices',
            field=models.ManyToManyField(blank=True, related_name='team_settings_list', to='cases.Stadium'),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='suggest_next_visit_choices',
            field=models.ManyToManyField(blank=True, related_name='team_settings_list', to='visits.SuggestNextVisit'),
        ),
    ]
