# Generated by Django 3.1.2 on 2020-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_auto_20201007_1226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamsettings",
            name="settings",
            field=models.JSONField(
                default={
                    "days": {
                        "friday": {
                            "day": {
                                "length_of_list": 6,
                                "primary_stadium": "Onderzoek buitendienst",
                                "secondary_stadia": ["2de Controle", "3de Controle"],
                            },
                            "evening": {
                                "length_of_list": 6,
                                "primary_stadium": "Avondronde",
                                "secondary_stadia": [
                                    "Hercontrole",
                                    "2de hercontrole",
                                    "3de hercontrole",
                                ],
                            },
                        },
                        "monday": {
                            "day": {
                                "length_of_list": 6,
                                "primary_stadium": "Onderzoek buitendienst",
                                "secondary_stadia": ["2de Controle", "3de Controle"],
                            },
                            "evening": {
                                "length_of_list": 6,
                                "primary_stadium": "Avondronde",
                                "secondary_stadia": [
                                    "Hercontrole",
                                    "2de hercontrole",
                                    "3de hercontrole",
                                ],
                            },
                        },
                        "saturday": {
                            "day": {
                                "length_of_list": 6,
                                "primary_stadium": "Weekend buitendienstonderzoek",
                                "secondary_stadia": [
                                    "Hercontrole",
                                    "2de hercontrole",
                                    "3de hercontrole",
                                ],
                            }
                        },
                        "sunday": {
                            "day": {
                                "length_of_list": 6,
                                "primary_stadium": "Weekend buitendienstonderzoek",
                                "secondary_stadia": [
                                    "Hercontrole",
                                    "2de hercontrole",
                                    "3de hercontrole",
                                ],
                            }
                        },
                        "thursday": {
                            "day": {
                                "length_of_list": 6,
                                "primary_stadium": "Onderzoek buitendienst",
                                "secondary_stadia": ["2de Controle", "3de Controle"],
                            },
                            "evening": {
                                "length_of_list": 6,
                                "primary_stadium": "Avondronde",
                                "secondary_stadia": [
                                    "Hercontrole",
                                    "2de hercontrole",
                                    "3de hercontrole",
                                ],
                            },
                        },
                        "tuesday": {
                            "day": {},
                            "evening": {
                                "length_of_list": 6,
                                "primary_stadium": "Avondronde",
                                "secondary_stadia": [
                                    "Hercontrole",
                                    "2de hercontrole",
                                    "3de hercontrole",
                                ],
                            },
                        },
                        "wednesday": {
                            "day": {},
                            "evening": {
                                "length_of_list": 6,
                                "primary_stadium": "Avondronde",
                                "secondary_stadia": [
                                    "Hercontrole",
                                    "2de hercontrole",
                                    "3de hercontrole",
                                ],
                            },
                        },
                    },
                    "opening_date": "2019-01-01",
                    "postal_codes": [{"range_end": 1109, "range_start": 1000}],
                    "projects": [
                        "Bed en breakfast 2019",
                        "Burgwallenproject Oudezijde",
                        "Corpo-rico",
                        "Digital toezicht Safari",
                        "Digital toezicht Zebra",
                        "Haarlemmerbuurt",
                        "Hotline",
                        "Mystery Guest",
                        "Project Andes",
                        "Project Jordaan",
                        "Project Lobith",
                        "Project Sahara",
                        "Safari",
                        "Safari 2015",
                        "Sahara Adams Suites",
                        "Sahara hele woning",
                        "Sahara meer dan 4",
                        "Sahara Recensies",
                        "Sahara veel adv",
                        "Social Media 2019",
                        "Woonschip (woonboot)",
                        "Zebra",
                    ],
                }
            ),
        ),
    ]
