# Generated by Django 3.1.2 on 2020-11-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0013_auto_20201102_0831"),
        ("planner", "0006_auto_20201028_1233"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsettings",
            name="observation_choices",
            field=models.ManyToManyField(
                blank=True, related_name="team_settings_list", to="visits.Observation"
            ),
        ),
        migrations.AddField(
            model_name="teamsettings",
            name="situation_choices",
            field=models.ManyToManyField(
                blank=True, related_name="team_settings_list", to="visits.Situation"
            ),
        ),
        migrations.AddField(
            model_name="teamsettings",
            name="suggest_next_visit_choices",
            field=models.ManyToManyField(
                blank=True,
                related_name="team_settings_list",
                to="visits.SuggestNextVisit",
            ),
        ),
    ]
