# Generated by Django 3.1.2 on 2020-11-02 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_auto_20201102_0831"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostalCodeRangeSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PostalCodeRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "range_start",
                    models.PositiveSmallIntegerField(
                        default=1000,
                        validators=[
                            django.core.validators.MaxValueValidator(9999),
                            django.core.validators.MinValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "range_end",
                    models.PositiveSmallIntegerField(
                        default=1000,
                        validators=[
                            django.core.validators.MaxValueValidator(9999),
                            django.core.validators.MinValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "postal_code_range_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postal_code_ranges",
                        to="planner.postalcoderangeset",
                    ),
                ),
            ],
        ),
    ]
