# Generated by Django 3.1.2 on 2020-11-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_remove_teamsettings_situation_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsettings",
            name="fraud_predict",
            field=models.BooleanField(default=True),
        ),
    ]
