# Generated by Django 3.1.2 on 2020-11-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_stadiumlabel"),
        ("planner", "0010_teamsettings_fraud_predict"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaySettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "week_day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            [0, "maandag"],
                            [1, "dinsdag"],
                            [2, "woensdag"],
                            [3, "donderdag"],
                            [4, "vrijdag"],
                            [5, "zaterdag"],
                            [6, "zondag"],
                        ]
                    ),
                ),
                ("opening_date", models.DateField(default="2019-01-01")),
                (
                    "postal_code_ranges",
                    models.JSONField(
                        default=[{"range_end": 1109, "range_start": 1000}]
                    ),
                ),
                ("length_of_list", models.PositiveSmallIntegerField(default=8)),
                (
                    "exclude_stadia",
                    models.ManyToManyField(
                        blank=True,
                        related_name="exclude_stadia_day_settings_list",
                        to="cases.Stadium",
                    ),
                ),
                (
                    "postal_code_ranges_presets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="postal_code_ranges_presets_day_settings_list",
                        to="planner.PostalCodeRangeSet",
                    ),
                ),
                (
                    "primary_stadium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_stadium_day_settings_list",
                        to="cases.stadium",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects_day_settings_list",
                        to="cases.Project",
                    ),
                ),
                (
                    "secondary_stadia",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_stadia_day_settings_list",
                        to="cases.Stadium",
                    ),
                ),
                (
                    "team_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_settings_list",
                        to="planner.teamsettings",
                    ),
                ),
            ],
            options={
                "ordering": ("week_day",),
            },
        ),
    ]
