# Generated by Django 3.1.2 on 2020-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0011_daysettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysettings",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="daysettings",
            name="week_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    [0, "zondag"],
                    [1, "maandag"],
                    [2, "dinsdag"],
                    [3, "woensdag"],
                    [4, "donderdag"],
                    [5, "vrijdag"],
                    [6, "zaterdag"],
                ],
                null=True,
            ),
        ),
    ]
