# Generated by Django 3.1.2 on 2020-11-18 10:06

import apps.planner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0013_auto_20201117_1556"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daysettings",
            name="postal_code_ranges",
            field=models.JSONField(
                default=apps.planner.models.day_settings__postal_code_ranges__default
            ),
        ),
    ]
