# Generated by Django 3.1.2 on 2020-11-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0014_auto_20201118_1006"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="daysettings",
            options={
                "ordering": ("week_day", "start_time"),
                "verbose_name_plural": "Day settings",
            },
        ),
        migrations.AlterModelOptions(
            name="teamsettings",
            options={"verbose_name_plural": "Team settings"},
        ),
    ]
