# Generated by Django 3.1.2 on 2020-11-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0015_auto_20201125_1947"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysettings",
            name="sia_presedence",
            field=models.BooleanField(default=False),
        ),
    ]
