# Generated by Django 3.1.2 on 2020-11-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0015_auto_20201126_1404"),
        ("planner", "0017_auto_20201126_1553"),
    ]

    operations = []
