# Generated by Django 3.1.2 on 2020-12-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0018_merge_20201130_1109"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamsettings",
            name="settings",
        ),
    ]
