# Generated by Django 3.1 on 2020-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fraudprediction", "0003_auto_20200318_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraudprediction",
            name="business_rules",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="fraudprediction",
            name="shap_values",
            field=models.JSONField(),
        ),
    ]
