# Generated by Django 2.1.11 on 2019-11-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("itinerary", "0011_auto_20191113_1516"),
    ]

    operations = [
        migrations.AlterModelOptions(name="itinerary", options={},),
        migrations.RemoveField(model_name="itinerary", name="date",),
        migrations.RemoveField(model_name="itinerary", name="team",),
        migrations.AddField(
            model_name="itinerary",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
