# Generated by Django 2.1.11 on 2019-11-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_auto_20191119_2146"),
        ("itinerary", "0013_auto_20191119_0959"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itineraryitem",
            name="address",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="adres_id",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="postal_code_area",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="postal_code_street",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="stadium",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="wng_id",
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="case",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="cases.Case",
            ),
        ),
    ]
