# Generated by Django 2.2.10 on 2020-03-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('itinerary', '0029_auto_20200305_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryteammember',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members',
                                    to='itinerary.Itinerary'),
        ),
    ]
