# Generated by Django 2.2.10 on 2020-04-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0038_itinerarysettings_start_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryitem",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
