# Generated by Django 2.2.10 on 2020-04-16 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itinerary", "0041_auto_20200414_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerarysettings",
            name="target_length",
            field=models.IntegerField(
                default=8,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
