# Generated by Django 3.0.7 on 2020-07-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0046_auto_20200706_1142"),
    ]

    operations = [
        migrations.RemoveField(model_name="postalcoderange", name="primary_stadium",),
        migrations.AddField(
            model_name="postalcoderange",
            name="itinerary_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postal_code_ranges",
                to="itinerary.ItinerarySettings",
            ),
        ),
    ]
