# Generated by Django 3.0.7 on 2020-07-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0051_auto_20200706_1220"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postalcodesettings",
            old_name="postal_code_range_end",
            new_name="range_end",
        ),
        migrations.RenameField(
            model_name="postalcodesettings",
            old_name="postal_code_range_start",
            new_name="range_start",
        ),
    ]
