# Generated by Django 3.1 on 2020-09-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_teamsettings_team_type'),
        ('itinerary', '0052_auto_20200706_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarysettings',
            name='team_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_team_settings', to='planner.teamsettings'),
        ),
    ]
