# Generated by Django 3.1.2 on 2020-10-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0053_itinerarysettings_team_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itineraryitem",
            name="checked",
        ),
    ]
