# Generated by Django 3.1.2 on 2020-11-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0056_itinerarysettings_day_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itinerarysettings",
            name="team_settings",
        ),
    ]
