# Generated by Django 3.1.2 on 2020-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0057_remove_itinerarysettings_team_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="external_state_id",
            field=models.IntegerField(null=True),
        ),
    ]
