# Generated by Django 3.1.2 on 2020-11-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0058_itinerary_external_state_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itinerary",
            name="external_state_id",
        ),
        migrations.AddField(
            model_name="itineraryitem",
            name="external_state_id",
            field=models.IntegerField(null=True),
        ),
    ]
