# Generated by Django 3.1.2 on 2020-11-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0059_auto_20201127_1301"),
        ("itinerary", "0058_itinerarysettings_sia_presedence"),
    ]

    operations = []
