# Generated by Django 2.1.11 on 2019-11-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_remove_case_stadion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="stadium",
            field=models.CharField(
                choices=[
                    ("IMD", "Issuemelding"),
                    ("ECE", "Eerste controle"),
                    ("TCE", "Tweede controle"),
                    ("DCE", "Derde controle"),
                    ("EHE", "Eerste hercontrole"),
                    ("THE", "Tweede hercontrole"),
                    ("DHE", "Derde hercontrole"),
                ],
                max_length=255,
            ),
        ),
    ]
