# Generated by Django 2.1.11 on 2019-11-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_auto_20191119_2139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case", name="postal_code", field=models.CharField(max_length=8),
        ),
    ]
