# Generated by Django 2.2.10 on 2020-03-09 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0007_project_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="state",
            old_name="state",
            new_name="name",
        ),
    ]
