# Generated by Django 2.2.10 on 2020-03-13 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0009_auto_20200309_1525"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={"ordering": ["case_id"]},
        ),
    ]
