# Generated by Django 2.2.10 on 2020-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0010_auto_20200313_1250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadium",
            name="name",
            field=models.CharField(
                choices=[
                    ("2de Controle", "2de Controle"),
                    ("2de hercontrole", "2de hercontrole"),
                    ("3de Controle", "3de Controle"),
                    ("3de hercontrole", "3de hercontrole"),
                    ("Avondronde", "Avondronde"),
                    ("Hercontrole", "Hercontrole"),
                    ("Onderzoek advertentie", "Onderzoek advertentie"),
                    ("Onderzoek buitendienst", "Onderzoek buitendienst"),
                    ("Weekend buitendienstonderzoek", "Weekend buitendienstonderzoek"),
                    ("Issuemelding", "Issuemelding"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
