# Generated by Django 2.2.10 on 2020-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0011_auto_20200317_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadium",
            name="name",
            field=models.CharField(
                choices=[
                    ("Onderzoek buitendienst", "Onderzoek buitendienst"),
                    ("2de Controle", "2de Controle"),
                    ("3de Controle", "3de Controle"),
                    ("Hercontrole", "Hercontrole"),
                    ("2de hercontrole", "2de hercontrole"),
                    ("3de hercontrole", "3de hercontrole"),
                    ("Avondronde", "Avondronde"),
                    ("Onderzoek advertentie", "Onderzoek advertentie"),
                    ("Weekend buitendienstonderzoek", "Weekend buitendienstonderzoek"),
                    ("Issuemelding", "Issuemelding"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
