# Generated by Django 3.1 on 2020-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_auto_20200916_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiaChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stadia', models.ManyToManyField(related_name='stadia_choices', to='cases.Stadium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('projects', models.ManyToManyField(related_name='project_choices', to='cases.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
