# Generated by Django 3.1 on 2020-10-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_auto_20201007_1226"),
    ]

    operations = [
        migrations.CreateModel(
            name="StadiumLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="sanctie", max_length=10)),
                (
                    "stadium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labels",
                        to="cases.stadium",
                    ),
                ),
            ],
        ),
    ]
