# Generated by Django 2.1.9 on 2019-11-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_auto_20191105_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='stadium',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
