# Generated by Django 3.0.7 on 2020-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="cooperation",
            field=models.BooleanField(null=True),
        ),
    ]
