# Generated by Django 3.0.7 on 2020-08-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0005_auto_20200810_0912"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="next_visit_can_go_ahead_description",
            new_name="can_next_visit_go_ahead_description",
        ),
        migrations.RenameField(
            model_name="visit",
            old_name="status",
            new_name="situation",
        ),
    ]
