# Generated by Django 3.0.7 on 2020-08-19 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0007_auto_20200818_0851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="can_next_visit_go_ahead_description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="observations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("malfunctioning_doorbell", "Bel functioneert niet"),
                        ("intercom", "Contact via intercom"),
                        ("hotel_furnished", "Hotelmatig ingericht"),
                        ("vacant", "Leegstaand"),
                        ("likely_inhabited", "Vermoedelijk bewoond"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="personal_notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="situation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nobody_present", "Niemand aanwezig"),
                    ("no_cooperation", "Geen medewerking"),
                    ("access_granted", "Toegang verleend"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="suggest_next_visit",
            field=models.CharField(
                choices=[
                    ("weekend", "Weekend"),
                    ("daytime", "Overdag"),
                    ("evening", "'s Avonds"),
                    ("unknown", "Onbekend"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="suggest_next_visit_description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
