# Generated by Django 3.1.2 on 2020-10-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0007_auto_20200818_0851"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fraud_probability", models.FloatField(null=True)),
                ("fraud_prediction", models.BooleanField(null=True)),
                ("business_rules", models.JSONField(null=True)),
                ("shap_values", models.JSONField(null=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_data",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
    ]
