# Generated by Django 3.1.2 on 2020-10-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itinerary", "0052_auto_20200706_1424"),
        ("cases", "0012_auto_20200407_1141"),
        ("visits", "0007_auto_20200818_0851"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_visits",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="thread_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="can_next_visit_go_ahead_description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="itinerary_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="itinerary.itineraryitem",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="personal_notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="suggest_next_visit_description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
