# Generated by Django 3.1 on 2020-08-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0008_auto_20200819_1411"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="thread_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
