# Generated by Django 3.1.2 on 2020-10-04 21:13

from django.db import migrations


class Migration(migrations.Migration):
    def connect_case_to_visit_via_itinerary_item(apps, schema_editor):
        Visit = apps.get_model("visits", "Visit")

        for visit in Visit.objects.all():
            visit.case = visit.itinerary_item.case
            visit.save()

    dependencies = [
        ("visits", "0008_auto_20201004_2109"),
    ]

    operations = [
        migrations.RunPython(
            connect_case_to_visit_via_itinerary_item, migrations.RunPython.noop
        ),
    ]
