# Generated by Django 3.1.2 on 2020-10-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0009_auto_20201006_1353"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitmetadata",
            old_name="business_rules",
            new_name="fraud_prediction_business_rules",
        ),
        migrations.RenameField(
            model_name="visitmetadata",
            old_name="shap_values",
            new_name="fraud_prediction_shap_values",
        ),
        migrations.RemoveField(
            model_name="visitmetadata",
            name="fraud_prediction",
        ),
    ]
