# Generated by Django 3.1.2 on 2020-10-04 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_auto_20200407_1141"),
        ("visits", "0009_auto_20201004_2113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_visits",
                to="cases.case",
            ),
        ),
    ]
