# Generated by Django 3.1.2 on 2020-10-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0010_auto_20201004_2119"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit", old_name="case", new_name="case_id",
        ),
    ]
