# Generated by Django 3.1.2 on 2020-10-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0011_auto_20201006_1149"),
        ("visits", "0010_auto_20201007_0833"),
    ]

    operations = []
