# Generated by Django 3.1.2 on 2020-11-02 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0012_merge_20201012_1110"),
    ]

    operations = [
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, unique=True)),
                ("verbose", models.CharField(max_length=100, unique=True)),
                ("position", models.FloatField()),
            ],
            options={
                "ordering": ("position",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Situation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, unique=True)),
                ("verbose", models.CharField(max_length=100, unique=True)),
                ("position", models.FloatField()),
            ],
            options={
                "ordering": ("position",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuggestNextVisit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, unique=True)),
                ("verbose", models.CharField(max_length=100, unique=True)),
                ("position", models.FloatField()),
            ],
            options={
                "ordering": ("position",),
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="visit",
            name="observations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="situation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="suggest_next_visit",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
