# Generated by Django 3.1.2 on 2020-11-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0013_auto_20201102_0831"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="thread_id",
        ),
    ]
